// Mocks generated by Mockito 5.4.6 from annotations
// in ecommerce/test/src/features/profile/domain/usecases/change_password_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ecommerce/src/core/error/failures.dart' as _i5;
import 'package:ecommerce/src/features/auth/domain/entities/user_entity.dart'
    as _i6;
import 'package:ecommerce/src/features/profile/domain/repositories/profile_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>> getCurrentProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentProfile, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserEntity>(
                    this,
                    Invocation.method(#getCurrentProfile, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>> updateProfile(
    _i6.UserEntity? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [user]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserEntity>(
                    this,
                    Invocation.method(#updateProfile, [user]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> updateProfilePicture(
    String? imagePath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePicture, [imagePath]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#updateProfilePicture, [imagePath]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> deleteProfile() =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#deleteProfile, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#changePassword, [], {
                  #currentPassword: currentPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
