// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnEGvJwi8PNxlzYisfhoCwYUuCsQqiWNw',
    appId: '1:684417284313:web:91350bc2cfde22e91526c8',
    messagingSenderId: '684417284313',
    projectId: 'ecommerce-38594',
    authDomain: 'ecommerce-38594.firebaseapp.com',
    storageBucket: 'ecommerce-38594.firebasestorage.app',
    measurementId: 'G-ZX9QKGD8EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClok2Hxmy-dYfCDWFQ2RkLwjDqeNMm0No',
    appId: '1:684417284313:android:7a16b8f8e43a99a81526c8',
    messagingSenderId: '684417284313',
    projectId: 'ecommerce-38594',
    storageBucket: 'ecommerce-38594.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuXlThUIeSmTyt-CNlQCxw4PdNwp1hY5s',
    appId: '1:684417284313:ios:234eef3e476c98721526c8',
    messagingSenderId: '684417284313',
    projectId: 'ecommerce-38594',
    storageBucket: 'ecommerce-38594.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuXlThUIeSmTyt-CNlQCxw4PdNwp1hY5s',
    appId: '1:684417284313:ios:234eef3e476c98721526c8',
    messagingSenderId: '684417284313',
    projectId: 'ecommerce-38594',
    storageBucket: 'ecommerce-38594.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnEGvJwi8PNxlzYisfhoCwYUuCsQqiWNw',
    appId: '1:684417284313:web:3fab97dc8f31791e1526c8',
    messagingSenderId: '684417284313',
    projectId: 'ecommerce-38594',
    authDomain: 'ecommerce-38594.firebaseapp.com',
    storageBucket: 'ecommerce-38594.firebasestorage.app',
    measurementId: 'G-L10KC1S29R',
  );
}
