// Mocks generated by Mockito 5.4.6 from annotations
// in ecommerce/test/src/features/profile/data/repositories/profile_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:connectivity_plus/connectivity_plus.dart' as _i8;
import 'package:ecommerce/src/core/network/network_info.dart' as _i7;
import 'package:ecommerce/src/features/auth/data/models/user_model.dart' as _i2;
import 'package:ecommerce/src/features/profile/data/datasources/profile_local_data_source.dart'
    as _i6;
import 'package:ecommerce/src/features/profile/data/datasources/profile_remote_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i3.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> getCurrentProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentProfile, []),
            returnValue: _i4.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#getCurrentProfile, [])),
            ),
          )
          as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<_i2.UserModel> updateProfile(_i2.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [user]),
            returnValue: _i4.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#updateProfile, [user])),
            ),
          )
          as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<String> updateProfilePicture(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePicture, [imagePath]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#updateProfilePicture, [imagePath]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteProfile() =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ProfileLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileLocalDataSource extends _i1.Mock
    implements _i6.ProfileLocalDataSource {
  MockProfileLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel?> getCachedProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProfile, []),
            returnValue: _i4.Future<_i2.UserModel?>.value(),
          )
          as _i4.Future<_i2.UserModel?>);

  @override
  _i4.Future<void> cacheProfile(_i2.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProfile, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCachedProfile() =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedProfile, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<List<_i8.ConnectivityResult>> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i4.Stream<List<_i8.ConnectivityResult>>.empty(),
          )
          as _i4.Stream<List<_i8.ConnectivityResult>>);
}
